config:
  # Runing mode
  #
  # - download: default mode, monitor URL and download when available
  # - metadata: download JSON metadata only
  # - notifier: only send notifications
  mode: download
  # There's no need to quote or escape your path, examples:
  #
  # - ~/Downlaods
  # - ~/Files/VTuber Videos
  # - ~/My Videos/Live Recordings
  #
  # All examples above should work
  output: ~/Downloads/VTuber Recordings
  interval: 5
  skip_alias: false
  skip_check: false
  skip_convert: false
  skip_metadata: false
  skip_email: true
  skip_slack: true
  skip_telegram: false
  run_callback: true
  address_pool: true
  image_proxy: false
  one_time: false
  timezone: Asia/Taipei
  email_provider: ses
  mailgun:
    # Find your private API key at https://app.mailgun.com/app/account/security/api_keys
    api: key-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    domain: mail.example.com
    receipt: me@example.com
  ses:
    access: AKxxxxxxxxxxxxxxxxxx
    secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    domain: mail.example.com
    receipt: me@example.com
  slack:
    # Create your webhook at https://slack.com/apps/A0F7XDUAZ-incoming-webhooks
    webhook: https://hooks.slack.com/services/
  telegram:
    # Obtian your bot API from @BotFather
    bot: 8*******6:A****E*******Fi****Y0****sSA*****sg
    # Get channel ID via:
    # https://api.telegram.org/bot<API-access-token>/getUpdates?offset=0
    channel: -1****35****28
  callback:
    executable: /root/live-dl_callback
  address_pool_file: /root/ipv6/address.txt
map:
  - name: Gawr Gura
    youtube: https://www.youtube.com/channel/UCoSrY_IQQVpmIRZ9Xf-y93g
    telegram: -1****35****28

  - name: Watson Amelia
    youtube: https://www.youtube.com/channel/UCyl1z3jo3XHR1riLFKG5UAg
    telegram: -1****35****28

  - name: Ninomae Ina'nis
    youtube: https://www.youtube.com/channel/UCMwGHR0BTZuLsmjY_NT5Pwg
    telegram: -1****35****28